### ISSUE TITLE
Intellij SonarLint Error

### ISSUE THREAD

**Issue by lalib** [SonarSource/sonarlint-core#1]
Hi there,

Sometimes it gives below error:

Error Message : Wrong line: 5. Available lines count: 5

Details : Wrong line: 5. Available lines count: 5
java.lang.IndexOutOfBoundsException: Wrong line: 5. Available lines count: 5
	at com.intellij.openapi.editor.impl.LineSet.a(LineSet.java:169)
	at com.intellij.openapi.editor.impl.LineSet.getLineStart(LineSet.java:154)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineStartOffset(DocumentImpl.java:890)
	at org.sonarlint.intellij.issue.IssueMatcher.findStartLineOffset(IssueMatcher.java:135)
	at org.sonarlint.intellij.issue.IssueMatcher.getIssueTextRange(IssueMatcher.java:112)
	at org.sonarlint.intellij.issue.IssueMatcher.match(IssueMatcher.java:86)
	at org.sonarlint.intellij.issue.IssueProcessor.transformIssues(IssueProcessor.java:101)
	at org.sonarlint.intellij.issue.IssueProcessor.process(IssueProcessor.java:65)
	at org.sonarlint.intellij.analysis.SonarLintTask.run(SonarLintTask.java:104)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

**Comment by dbmeneses** [comment]
Thanks for reporting this.
This problem was already reported in the tracker that this project uses: https://jira.sonarsource.com/browse/SLI-31.
I've added your stack for reference.
